/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChiSiamoRouteImport } from './routes/chi-siamo'
import { Route as ContattiRouteImport } from './routes/contatti'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as DolciRouteImport } from './routes/dolci'
import { Route as EventiRouteImport } from './routes/eventi'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RecensioniRouteImport } from './routes/recensioni'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TerminiRouteImport } from './routes/termini'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChiSiamoRoute = ChiSiamoRouteImport.update({
  id: '/chi-siamo',
  path: '/chi-siamo',
  getParentRoute: () => rootRouteImport,
} as any)
const ContattiRoute = ContattiRouteImport.update({
  id: '/contatti',
  path: '/contatti',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const DolciRoute = DolciRouteImport.update({
  id: '/dolci',
  path: '/dolci',
  getParentRoute: () => rootRouteImport,
} as any)
const EventiRoute = EventiRouteImport.update({
  id: '/eventi',
  path: '/eventi',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RecensioniRoute = RecensioniRouteImport.update({
  id: '/recensioni',
  path: '/recensioni',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminiRoute = TerminiRouteImport.update({
  id: '/termini',
  path: '/termini',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chi-siamo': typeof ChiSiamoRoute
  '/contatti': typeof ContattiRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/dolci': typeof DolciRoute
  '/eventi': typeof EventiRoute
  '/gallery': typeof GalleryRoute
  '/menu': typeof MenuRoute
  '/privacy': typeof PrivacyRoute
  '/recensioni': typeof RecensioniRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termini': typeof TerminiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chi-siamo': typeof ChiSiamoRoute
  '/contatti': typeof ContattiRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/dolci': typeof DolciRoute
  '/eventi': typeof EventiRoute
  '/gallery': typeof GalleryRoute
  '/menu': typeof MenuRoute
  '/privacy': typeof PrivacyRoute
  '/recensioni': typeof RecensioniRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termini': typeof TerminiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chi-siamo': typeof ChiSiamoRoute
  '/contatti': typeof ContattiRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/dolci': typeof DolciRoute
  '/eventi': typeof EventiRoute
  '/gallery': typeof GalleryRoute
  '/menu': typeof MenuRoute
  '/privacy': typeof PrivacyRoute
  '/recensioni': typeof RecensioniRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termini': typeof TerminiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chi-siamo'
    | '/contatti'
    | '/cookie-policy'
    | '/dolci'
    | '/eventi'
    | '/gallery'
    | '/menu'
    | '/privacy'
    | '/recensioni'
    | '/sitemap.xml'
    | '/termini'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chi-siamo'
    | '/contatti'
    | '/cookie-policy'
    | '/dolci'
    | '/eventi'
    | '/gallery'
    | '/menu'
    | '/privacy'
    | '/recensioni'
    | '/sitemap.xml'
    | '/termini'
  id:
    | '__root__'
    | '/'
    | '/chi-siamo'
    | '/contatti'
    | '/cookie-policy'
    | '/dolci'
    | '/eventi'
    | '/gallery'
    | '/menu'
    | '/privacy'
    | '/recensioni'
    | '/sitemap.xml'
    | '/termini'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChiSiamoRoute: typeof ChiSiamoRoute
  ContattiRoute: typeof ContattiRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  DolciRoute: typeof DolciRoute
  EventiRoute: typeof EventiRoute
  GalleryRoute: typeof GalleryRoute
  MenuRoute: typeof MenuRoute
  PrivacyRoute: typeof PrivacyRoute
  RecensioniRoute: typeof RecensioniRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TerminiRoute: typeof TerminiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chi-siamo': {
      id: '/chi-siamo'
      path: '/chi-siamo'
      fullPath: '/chi-siamo'
      preLoaderRoute: typeof ChiSiamoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatti': {
      id: '/contatti'
      path: '/contatti'
      fullPath: '/contatti'
      preLoaderRoute: typeof ContattiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dolci': {
      id: '/dolci'
      path: '/dolci'
      fullPath: '/dolci'
      preLoaderRoute: typeof DolciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventi': {
      id: '/eventi'
      path: '/eventi'
      fullPath: '/eventi'
      preLoaderRoute: typeof EventiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recensioni': {
      id: '/recensioni'
      path: '/recensioni'
      fullPath: '/recensioni'
      preLoaderRoute: typeof RecensioniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termini': {
      id: '/termini'
      path: '/termini'
      fullPath: '/termini'
      preLoaderRoute: typeof TerminiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChiSiamoRoute: ChiSiamoRoute,
  ContattiRoute: ContattiRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  DolciRoute: DolciRoute,
  EventiRoute: EventiRoute,
  GalleryRoute: GalleryRoute,
  MenuRoute: MenuRoute,
  PrivacyRoute: PrivacyRoute,
  RecensioniRoute: RecensioniRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TerminiRoute: TerminiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
